---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lin.
--- DateTime: 2023/3/24 12:00
---

-- 判断库存是否充足
-- 判断是否下单

local voucherId = ARGV[1]
local userId = ARGV[2]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--业务流程
if(tonumber(redis.call('get',stockKey))<=0)then
    -- 库存不足
    return 1
end

if(redis.call('sismember',orderKey,userId)==1)then
    -- 重复下单
    return 2
end

-- 扣库存 保存订单
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)

return 0
